### ISSUE TITLE
Ensure error message is an unicode object and not utf-8 bytestring

### ISSUE THREAD

**Issue by mtrebron** [plone/plone.app.contentrules#24]
In workflow.py the error statusmessage "message" (unicode) is composed using a title and error - both values are apparently bytestrings. Translating the statusmessage then [fails in zope.i18n](https://github.com/zopefoundation/zope.i18n/issues/23)

```
  Module plone.app.contentrules.actions.workflow, line 77, in error
  Module Products.statusmessages.adapter, line 34, in add
  Module zope.i18n, line 127, in translate
  Module zope.i18n.translationdomain, line 78, in translate
  Module zope.i18n.translationdomain, line 140, in _recursive_translate
  Module zope.i18n, line 165, in interpolate
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 15: ordinal not in range(128)
```

Ensuring that title and error are indeed unicode fixes the issue:

```
    -        title = utils.pretty_title_or_id(obj, obj)
    +        title = utils.safe_unicode(utils.pretty_title_or_id(obj, obj))
    +        error = utils.safe_unicode(error)
```

**Comment by gforcada** [comment]
Hi @mtrebron thanks for filling this issue and on top of that already providing a way to fix it :100:

To keep attribution where it belongs, would you mind creating a pull request with that small change?

I see that you seem to not have signed [Plone's CLA](http://docs.plone.org/develop/coredev/docs/contributors_agreement_explained.html'), is a really easy one time only process (download a PDF, print, sign, scan and send via email) which will enable you to make as much contributions to Plone as you wish. Let us know if we can help you in any way.

**Comment by mtrebron** [comment]
@gforcada - CLA sent in

**Comment by gforcada** [comment]
Thanks! Welcome to Plone!

**Comment by mtrebron** [comment]
Closing, fix merged here https://github.com/plone/plone.app.contentrules/pull/29
