### ISSUE TITLE
"Missing" versioning action?

### ISSUE THREAD

**Issue by gbastien** [plone/plone.app.contentrules#44]
Hi @pbauer @mauritsvanrees @jensens 

we need a "versioning" action so a content is versioned when it is published for example.

I think this could be part of this package instead a separated package, do you agree?

If so I will propose a PR.

Thank you,

Gauthier

**Comment by gbastien** [comment]
Hi @esteele @mauritsvanrees 

I saw there was a new release of 4.1.x branch, is it possible to have a new release for branch 4.0.x so we have a version compatible with Plone 5.1.x?

Thank you!

Gauthier

**Comment by mauritsvanrees** [comment]
Sure. I have released 4.0.19.
