### ISSUE TITLE
House keeping: Update troove classifiers and check install_requires

### ISSUE THREAD

**Issue by jensens** [plone/plone.app.contentrules#46]
- `.. :: Zope2` is still in the troove classifiers
- `Framework :: Plone :: Plone Core` is missing
- IIRC `ZODB3` is no longer needed with Plone 5.2/ Zope 4  as `install_requires`

**Comment by mauritsvanrees** [comment]
The classifiers were already fixed meanwhile.
I have updated the dependencies in a direct commit on master.
