### ISSUE TITLE
Update markup of templates to Bootstrap 5

### ISSUE THREAD

**Issue by santonelli** [plone/plone.app.contentrules#53]
Due to #2967 we have to update the markup of the templates listed below. 

Updated:

- [x] plone.app.contentrules.browser.templates.controlpanel.pt
- [x] plone.app.contentrules.browser.templates.manage-assignments.pt
- [x] plone.app.contentrules.browser.templates.manage-elements.pt

Unknown:

- [x] plone.app.contentrules.browser.templates.contentrules-pageform.pt

Feel free to add missing templates here. See also #3061 for further details. Check overrides in [plonetheme.tokyo](https://github.com/collective/plonetheme.tokyo) for already existing updated templates.

**Comment by petschki** [comment]
I consider this as done ... see latest PR #67
